### ISSUE TITLE
Entering & storing payments information

### ISSUE THREAD

**Issue by cellacecilia** [CustomersDevops/customers#4]
**As a customer** 
**I need to enter and save payment information**  
**So that I can seamlessly and securely place future orders**  

**Assumptions:** 
* Customers want this convenience.
* Customers trust our website to safely hold their payment information. 

**Acceptance Criteria:**
```
Given that a customer needs to pay for an order
When they are placing an order
Then they can enter payment details once and have it saved for future transactions
```

**Comment by ajmical** [comment]
testing zenhub extension
