### ISSUE TITLE
Saving multiple shipping addresses

### ISSUE THREAD

**Issue by cellacecilia** [CustomersDevops/customers#5]
**As a customer**   
**I need to save multiple shipping addresses**  
**So that I can easily select a shipping address on future orders**  

**Assumptions:** 
* Customers sometimes ship to more than one address
* Customers want the convenience of selecting a commonly used address versus typing it in every time

**Acceptance Criteria:**
```
Given that a customer orders to multiple addresses
When they need to send an order to an address other than their primary home address
Then they will want to be able to save multiple shipping address and select from them upon placing an order
```

**Comment by sklimova** [comment]
Added medium priority to the story
