### ISSUE TITLE
Create a BDD .feature file and accompanying steps.py files to test your RESTful API from the outside in.

### ISSUE THREAD

**Issue by teddycallahan** [CustomersDevops/customers#60]
**As a** ...  
**I need** ...  
**So that** ...  

**Assumptions:** 
* ...

**Acceptance Criteria:**
```
Given ...
When ...
Then ...
```

**Comment by ajmical** [comment]
@sklimova it appears this step was completed with our most recent pull request - as 
I can see both of these files nested under the "steps" folder in VSCode. Let me know if I'm missing something, but I think we can mark this issue as complete.
